### ISSUE TITLE
Wallpapers Are Not Changing

### ISSUE THREAD

**Issue by ikramul04** [t1m0thyj/WinDynamicDesktop#27]
Now i have another problem.my wallpapers dont change if i update my location then it changes plz fix it

**Comment by t1m0thyj** [comment]
Are you using the latest version? This should be fixed in version 1.2.2 which I released last night.

**Comment by jcesar18** [comment]
using lates version the wallpapers still don't updated same wallpaper since installation 2 days back tried uninstall and instal but noting please help

**Comment by t1m0thyj** [comment]
Unfortunately I can't reproduce this error, so it's going to be difficult for me to fix. What version of Windows are you running?

Also, could anyone who is experiencing this problem check and see if there's a `WinDynamicDesktop.exe.log` file in the same folder as the app? If so please paste the contents in a comment here, the information in that file might help to determine the cause of the problem.

**Comment by jcesar18** [comment]
windows 10 pro version 1803 64 bit also opening the imagen folder there is only one set of pictures the other are not properly installed on it and I could not find the other one your are asking for

**Comment by zhaoyupingcn** [comment]
i have the same problem and im using ver1.2.3.   the app dont auto refresh wallpaper all day. you can only change the wallpaper by click the menu. or reboot the app/system. pls check it .thx

os ver win7 64bit

**Comment by sotiriszampras** [comment]
I have Windows 10 Pro 1803 64bit
There isn't any log file at the promgram's install location

**Comment by t1m0thyj** [comment]
Is anyone still experiencing this problem in the latest version (1.4)? If so, could you please exit the app from the system tray, then navigate to the folder where the app is installed and delete the following:

- `images` folder
- `images.zip` file (if it exists)
- `settings.conf` file

After deleting those files, run the app again and after entering your location see if the problem still exists.

**Comment by t1m0thyj** [comment]
I should have thought to ask this sooner, is your copy of Windows 10 activated? If it isn't, then Microsoft doesn't allow changing the desktop wallpaper.

**Comment by sotiriszampras** [comment]
It works for me now

**Comment by t1m0thyj** [comment]
Since no one else has commented for over a month, I'm assuming this has been fixed.

**Comment by joosebox** [comment]
> Is anyone still experiencing this problem in the latest version (1.4)? If so, could you please exit the app from the system tray, then navigate to the folder where the app is installed and delete the following:
> 
> * `images` folder
> * `images.zip` file (if it exists)
> * `settings.conf` file
> 
> After deleting those files, run the app again and after entering your location see if the problem still exists.

I'm having this issue on a Surface Pro 6. It works fine on my desktop PC. I want to try the steps mentioned in this post, but I cannot for the life of me find where the Windows Store installed the executable. Do you by chance know where the Windows Store installs this? 

Thanks in advance!

**Comment by t1m0thyj** [comment]
@joosebox The folder where the app package is located is likely `%LOCALAPPDATA%\Packages\38719TimothyJohnson.WinDynamicDesktop_rfarkse4rn21a\LocalState`. You can type `%LOCALAPPDATA%` into Windows Explorer, it will evaluate to `C:\Users\{username}\AppData\Local`. Also I'm not sure if the ID in the folder name will be exactly the same for you but if not it should still be easy to find in the `Packages` folder. Please also check if there is a `WinDynamicDesktop.exe.log` file in that folder and if so attach the contents.

**Comment by joosebox** [comment]
> @joosebox The folder where the app package is located is likely `%LOCALAPPDATA%\Packages\38719TimothyJohnson.WinDynamicDesktop_rfarkse4rn21a\LocalState`. You can type `%LOCALAPPDATA%` into Windows Explorer, it will evaluate to `C:\Users\{username}\AppData\Local`. Also I'm not sure if the ID in the folder name will be exactly the same for you but if not it should still be easy to find in the `Packages` folder. Please check if there is a `WinDynamicDesktop.exe.log` file in that folder and if so attach the contents.

Thanks so much for the prompt response. And sorry for not being more descriptive originally. I should've said both machines are running 1809 and version 2.2.0.0 of your app. Thanks to your help, I was able to locate the folder. I deleted `images` and `settings.conf` (did not have an `images.zip`). I also didn't see a `WinDynamicDesktop.exe.log`, (in `LocalState` or the root program folder). 

I'm going to give it a few cycles and see if deleting that folder and file works. Will let you know if not!
